[project]
name = "clashofclans"
version = "0.1.0"
description = "Get the COC static data in JSON format."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.12.15",
    "pylzham>=0.1.3",
    "zstandard>=0.24.0",
]
